### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by n1000g** [Aphcity/2022_BJTU_CSKaoyan#2]
研友吗，我有大三上课的PPT，需要话邮件发你，但没法开源

**Comment by Aphcity** [comment]
啊啊啊是的，如果可以的话，不胜感激了QAQ

n1000g ***@***.***> 于2021年9月17日周五 下午8:17写道：

**Comment by n1000g** [comment]
发你gmail邮箱了

**Comment by Aphcity** [comment]
> 发你gmail邮箱了

好的好的👌，蟹蟹辣QWQ
